Fix pendantic warning in gcc 7.3
/include/experimental/bits/static_thread_pool.h:82:105: error: extra ‘;’ [-Werror=pedantic]
         require(const execution::allocator_t<NewProtoAllocator>& a) const { return {pool_, a.value()}; };
                                                                                                         ^